   
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" href="images/fav.png"/>
    <title>
        <?php if(isset($title))
                    echo $title; 

                else echo "Abhikalpan'16 | Annual Technical Festival IIITDM Jabalpur";

        ?>
    </title>
    <meta name="description" content="Witness wide range of technical events in the domain of mechanical, computer science, electronics, robotics, design & management with various other exhibitions & most inspiring workhops on current technologies.">
    

    <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">

   <link rel="stylesheet" href="css/bootstrap.css">
   <link rel="stylesheet" href="css/flexslider.css">
 
    <link rel="stylesheet" href="css/jquery.parallax.css" />
    <link rel="stylesheet" href="css/animate.css" type="text/css">
   
    <!-- <link rel="stylesheet" href="css/nanoscroller.css" type="text/css"> -->
    <link rel="stylesheet" href="perfect-scrollbar.css" type="text/css">
    <link rel="stylesheet" href="css/style.css" type="text/css">
    

    <script src="js/jquery.js"></script>
    <script src="js/jquery.flexslider-min.js"></script>
    
	
	
	
		

<link rel="shortcut icon" href="img/logo.png"/>

		
		<link rel="stylesheet" type="text/css" href="css/component2.css" />
		<script src="js/modernizr-2.6.2.min.js"></script>



	<script src="js/demo2.js"></script>
	<link rel="stylesheet" type="text/css" href="css/effect.css" />
		<link rel="stylesheet" type="text/css" href="css/style1.css" />
	
			<link rel="stylesheet" type="text/css" href="css/social.css" />	
			
				<link href='http://fonts.googleapis.com/css?family=Cabin:400,500,600,700,400italic,500italic,600italic,700italic' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		